version: '3.1'

services:
  mariadb:
    image: mariadb:10.5.5
    container_name: "mariadb1"
    restart: no
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
